### ISSUE TITLE
Spigot 1.8.8 Startup Error

### ISSUE THREAD

**Issue by w1nst0nDEV** [InventivetalentDev/MapManager#30] opened 2019-03-15 18:28 UTC
**When does this error occur?** Startup of Spigot 1.8.8, latest version.

**What effects does it have?** It completely disables the plugin.

**What's the error?** The error can be viewed on [this pastebin](https://pastebin.com/TFkPSiDt).

**Do you have all dependencies installed?** Yes. I have PacketListenerAPI installed.

**Comment by Th3Shadowbroker** [comment] 2019-03-16 12:17
Hi @w1nst0nDEV, which version of PacketListenerAPI are you using?

**Comment by w1nst0nDEV** [comment] 2019-03-16 12:30
https://github.com/InventivetalentDev/MapManager/issues/30#issuecomment-473525235

I am using 3.7.1_SNAPSHOT. Am I supposed to use a different version?

**Comment by Th3Shadowbroker** [comment] 2019-03-16 13:22
I were able to reproduce and solve the described problem.
I've used spigot 1.8.8-R0.1-SNAPSHOT and PacketListenerAPI 3.7.1_SNAPSHOT combined with the MapManager v1.7.2-SNAPSHOT as you described and the same error occurred. However I were able to solve it in the end by replacing the PacketListenerAPI v3.7.1_SNAPSHOT with 3.7.2-SNAPSHOT. 3.7.2-SNAPSHOT is not available on spigot at the moment, so I will attach it to my comment.

[PacketListenerAPI_v3.7.2-SNAPSHOT.zip](https://github.com/InventivetalentDev/MapManager/files/2973928/PacketListenerAPI_v3.7.2-SNAPSHOT.zip)

Let me know if this solved your problem or if it still persists (for whatever reason). 😄 

EDIT: So in the end, this is a duplicate of #29

**Comment by w1nst0nDEV** [comment] 2019-03-17 00:50
> I were able to reproduce and solve the described problem.
> I've used spigot 1.8.8-R0.1-SNAPSHOT and PacketListenerAPI 3.7.1_SNAPSHOT combined with the MapManager v1.7.2-SNAPSHOT as you described and the same error occurred. However I were able to solve it in the end by replacing the PacketListenerAPI v3.7.1_SNAPSHOT with 3.7.2-SNAPSHOT. 3.7.2-SNAPSHOT is not available on spigot at the moment, so I will attach it to my comment.
> 
> [PacketListenerAPI_v3.7.2-SNAPSHOT.zip](https://github.com/InventivetalentDev/MapManager/files/2973928/PacketListenerAPI_v3.7.2-SNAPSHOT.zip)
> 
> Let me know if this solved your problem or if it still persists (for whatever reason). 😄
> 
> EDIT: So in the end, this is a duplicate of #29

Works perfectly! I'll look at closed issues if I encounter any type of error again from now on! (If it's no where to be found, I'll submit a new issue!)

**Closed as completed** 2019-03-17 00:50 UTC
